// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPZ8aG4HH_j174DXjZTfaJvJ-aWYG84j8',
    appId: '1:1077399810895:web:1db4a5cd183560e6240b3a',
    messagingSenderId: '1077399810895',
    projectId: 'expensetracker-6943e',
    authDomain: 'expensetracker-6943e.firebaseapp.com',
    storageBucket: 'expensetracker-6943e.appspot.com',
    measurementId: 'G-V4V1L0YF7J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhcsK-c7f-bHUSkDmgqyddwei4f4H70N0',
    appId: '1:1077399810895:android:3fe2911a6096223e240b3a',
    messagingSenderId: '1077399810895',
    projectId: 'expensetracker-6943e',
    storageBucket: 'expensetracker-6943e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe4fSRR2Pq-dHTabyltAdHKei42KCow0Y',
    appId: '1:1077399810895:ios:310486dab2f841f2240b3a',
    messagingSenderId: '1077399810895',
    projectId: 'expensetracker-6943e',
    storageBucket: 'expensetracker-6943e.appspot.com',
    iosBundleId: 'com.example.athangExpenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAe4fSRR2Pq-dHTabyltAdHKei42KCow0Y',
    appId: '1:1077399810895:ios:310486dab2f841f2240b3a',
    messagingSenderId: '1077399810895',
    projectId: 'expensetracker-6943e',
    storageBucket: 'expensetracker-6943e.appspot.com',
    iosBundleId: 'com.example.athangExpenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPZ8aG4HH_j174DXjZTfaJvJ-aWYG84j8',
    appId: '1:1077399810895:web:3cc8ccd1752ae2fa240b3a',
    messagingSenderId: '1077399810895',
    projectId: 'expensetracker-6943e',
    authDomain: 'expensetracker-6943e.firebaseapp.com',
    storageBucket: 'expensetracker-6943e.appspot.com',
    measurementId: 'G-LN0G62YK6S',
  );
}
